# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-30 21:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_auto_20180730_2135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='created_date',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='modified_date',
            new_name='modified',
        ),
    ]
