# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-31 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0004_auto_20180730_2138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default=None, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='blog',
            unique_together=set([('slug',)]),
        ),
    ]
