# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-31 20:46
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0006_auto_20180731_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together=set([('slug',)]),
        ),
        migrations.AddField(
            model_name='blog',
            name='related_topics',
            field=models.ManyToManyField(related_name='related_topics', to='log.Topic'),
        ),
    ]
